<a target="_blank" href="https://colab.research.google.com/github/thinh-vu/vnstock/blob/main/docs/1_vietnam_stock_vnstock3.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Mục lục

1. Chứng khoán Việt Nam [tại đây](https://colab.research.google.com/github/thinh-vu/vnstock/blob/main/docs/1_vietnam_stock_vnstock3.ipynb)
2. Chứng khoán quốc tế: Forex, Crypto, Chỉ số [tại đây](https://colab.research.google.com/github/thinh-vu/vnstock/blob/main/docs/2_international_market.ipynb)
3. Dữ liệu Thị trường, hàng hoá [tại đây](https://colab.research.google.com/github/thinh-vu/vnstock/blob/main/docs/3_commodities_vnstock3.ipynb)
4. Biểu diễn dữ liệu trực quan từ Vnstock3 [tại đây](https://colab.research.google.com/github/thinh-vu/vnstock/blob/main/docs/5_visualization_data_exploration_vnstock3.ipynb)

# I. Cài đặt

## Cài đặt thư viện

In [ ]:
!pip install -U vnstock3

## Tự động chấp nhận thoả thuận người dùng

Trong trường hợp bạn sử dụng Vnstock3 trên Google Colab (hoặc các môi trường không có giao diện nhập liêụ), việc hiển thị thoả thuận người dùng mỗi lần khởi động phiên làm việc có thể khiến bạn phiền lòng, hãy đặt đoạn code này trước dòng lệnh nạp thư viện vnstock3 để tự động chấp nhận và bỏ qua bước yêu cầu chấp nhận thoả thuận sử dụng.

In [ ]:
import os
if "ACCEPT_TC" not in os.environ:
    os.environ["ACCEPT_TC"] = "tôi đồng ý"

## Nạp thư viện lần đầu

> Bạn có thể nạp toàn bộ các module của thư viện vào môi trường làm việc nếu chưa biết rõ mình cần gì hoặc chọn từng module riêng biệt để nạp vào khi đã quen thuộc.

In [ ]:
## Nạp toàn bộ thư viện
# from vnstock3 import *

## Nạp Wrapper làm việc chính (UI chính của thư viện)
from vnstock3 import Vnstock

# II. Truy xuất dữ liệu - CK Việt Nam

* Khởi tạo đối tượng stock để dùng cho tất cả thao tác truy xuất dữ liệu chứng khoán về sau. Luồng công việc minh hoạ dưới đây giả định bạn bắt đầu với 1 mã chứng khoán cần phân tích, mặc định là VN30F1M. Bạn có thể thay đổi sang mã bất kỳ bằng cách nhập tham số `symbol` tại hàm chức năng thay vì khởi tạo lại đối tượng. Ví dụ, mã `VN30F1M` được gán khi tạo đối tượng, nhưng khi gọi dữ liệu giá lịch sử, bạn có thể cập nhật mã mới là `ACB` thay vì khởi tạo lại đối tượng một cách bất tiện: `stock.quote.history(symbol='ACB', start='2020-01-01', end='2024-12-31')`

* Chọn nguồn dữ liệu thuộc danh sách được hỗ trợ: VCI, TCBS cho chứng khoán trong nước, MSN cho dữ liệu chứng khoán quốc tế và sàn HOSE.

In [2]:
from vnstock3 import Vnstock
stock = Vnstock().stock(symbol='VN30F1M', source='VCI')

2024-06-16 14:48:20,252 - vnstock3.common.data.data_explorer - WARNING - Thông tin niêm yết & giao dịch sẽ được truy xuất từ TCBS

## Listing: Liệt kê danh sách chứng khoán

### Danh sách tất cả mã CK niêm yết (đơn giản)

In [3]:
# VCI là nguồn dữ liệu từ CK Vietcap bên cạnh nguồn từ TCBS
stock.listing.all_symbols()

     ticker                                         organ_name
0       A32                                 Công ty Cổ phần 32
1       AAA                  Công ty Cổ phần Nhựa An Phát Xanh
2       AAM                    Công ty Cổ Phần Thủy Sản MeKong
3       AAS            Công ty Cổ phần Chứng khoán SmartInvest
4       AAT        Công ty Cổ phần Tập đoàn Tiên Sơn Thanh Hóa
...     ...                                                ...
1593    XPH                    Công ty Cổ phần Xà phòng Hà Nội
1594    YBC      Công ty Cổ phần Xi măng và Khoáng sản Yên Bái
1595    YBM     Công ty Cổ phần Khoáng sản Công nghiệp Yên Bái
1596    YEG                     Công ty Cổ phần Tập đoàn Yeah1
1597    YTC  Công ty Cổ phần Xuất nhập khẩu Y tế Thành phố ...

[1598 rows x 2 columns]

### Liệt kê mã CP theo sàn (đầy đủ)

In [4]:
# Dữ liệu bao gồm tất cả các mã không kể đang niêm yết hay không
stock.listing.symbols_by_exchange()

,symbol,id,type,exchange,en_organ_name,en_organ_short_name,organ_short_name,organ_name
0,YTC,8425620,STOCK,UPCOM,Ho Chi Minh City Medical Import Export Joint S...,YTECO,XNK Y tế TP.HCM,Công ty Cổ phần Xuất nhập khẩu Y tế Thành phố ...
1,YEG,8424579,STOCK,HSX,Yeah1 Group Corporation,Yeah1 Group,Tập đoàn Yeah1,Công ty Cổ phần Tập đoàn Yeah1
2,YBM,8424470,STOCK,HSX,Yen Bai Industry Mineral Joint Stock Company,Yen Bai Industry Mineral,Khoáng sản CN Yên Bái,Công ty Cổ phần Khoáng sản Công nghiệp Yên Bái
3,YBC,8425710,STOCK,UPCOM,YenBai Cement and Minerals Joint Stock Company,YenBai Cement and Minerals,Xi măng và Khoáng sản Yên Bái,Công ty Cổ phần Xi măng và Khoáng sản Yên Bái
4,XPH,8425864,STOCK,UPCOM,Hanoi Soap Joint Stock Company,Hanoi Soap,Xà phòng Hà Nội,Công ty Cổ phần Xà phòng Hà Nội
...,...,...,...,...,...,...,...,...
2474,AAS,8425599,STOCK,UPCOM,Smart Invest Securities Joint Stock Company,SmartInvest Securities,Chứng khoán SmartInvest,Công ty Cổ phần Chứng khoán SmartInvest
2475,AAM,8424957,STOCK,HSX,Mekong Fisheries Joint Stock Company,Mekong Fisheries,Thủy sản Mekong,Công ty Cổ Phần Thủy Sản MeKong
2476,AAH,13216673,STOCK,UPCOM,Hop Nhat Joint Stock Company,Hop Nhat Coal,Than Hợp Nhất,Công ty Cổ phần Hợp Nhất
2477,AAA,8424464,STOCK,HSX,An Phat Bioplastics Joint Stock Company,An Phat Bioplastics,An Phát Bioplastics,Công ty Cổ phần Nhựa An Phát Xanh
2478,A32,8425330,STOCK,UPCOM,32 Joint Stock Company,32 Company,Công ty 32,Công ty Cổ phần 32

### Liệt kê mã CP theo ngành icb

In [3]:
stock.listing.symbols_by_industries()

,symbol,organ_name,en_organ_name,icb_name3,en_icb_name3,icb_name2,en_icb_name2,icb_name4,en_icb_name4,com_type_code,icb_code1,icb_code2,icb_code3,icb_code4
0,HIO,Công ty Cổ Phần Helio Energy,Helio Energy Joint Stock Company,Sản xuất & Phân phối Điện,Electricity,"Điện, nước & xăng dầu khí đốt",Utilities,Sản xuất & Phân phối Điện,Conventional Electricity,CT,7000,7500,7530,7535
1,CST,Công ty Cổ phần Than Cao Sơn - TKV,Cao Son Coal Joint Stock Company,Khai khoáng,Mining,Tài nguyên Cơ bản,Basic Resources,Khai thác Than,Coal,CT,1000,1700,1770,1771
2,SGI,Công ty Cổ phần Đầu tư phát triển Sài Gòn 3 Group,Sai Gon 3 Group Investment Development Joint S...,Hàng cá nhân,Personal Goods,Hàng cá nhân & Gia dụng,Personal & Household Goods,Hàng May mặc,Clothing & Accessories,CT,3000,3700,3760,3763
3,TOS,Công ty Cổ phần Dịch vụ biển Tân Cảng,Tan Cang Offshore Services Joint Stock Company,"Thiết bị, Dịch vụ và Phân phối Dầu khí","Oil Equipment, Services & Distribution",Dầu khí,Oil & Gas,Thiết bị và Dịch vụ Dầu khí,Oil Equipment & Services,CT,0001,0500,0570,0573
4,DSD,Công ty cổ phần DHC Suối Đôi,DHC Suoi Doi Corporation,Du lịch & Giải trí,Travel & Leisure,Du lịch và Giải trí,Travel & Leisure,Dịch vụ giải trí,Recreational Services,CT,5000,5700,5750,5755
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1585,VRE,Công ty Cổ phần Vincom Retail,Vincom Retail Joint Stock Company,Bất động sản,Real Estate Investment & Services,Bất động sản,Real Estate,Bất động sản,Real Estate Holding & Development,CT,8000,8600,8630,8633
1586,VTV,Công ty Cổ phần Năng lượng và Môi trường VICEM,VICEM Energy And Environment Joint Stock Company,Xây dựng và Vật liệu,Construction & Materials,Xây dựng và Vật liệu,Construction & Materials,Vật liệu xây dựng & Nội thất,Building Materials & Fixtures,CT,2000,2300,2350,2353
1587,CAB,Công ty Cổ phần Tổng Công ty Truyền hình Cáp V...,Vietnam Television Cable Joint Stock Company,Truyền thông,Media,Truyền thông,Media,Giải trí & Truyền thông,Broadcasting & Entertainment,CT,5000,5500,5550,5553
1588,XPH,Công ty Cổ phần Xà phòng Hà Nội,Hanoi Soap Joint Stock Company,Hàng cá nhân,Personal Goods,Hàng cá nhân & Gia dụng,Personal & Household Goods,Hàng cá nhân,Personal Products,CT,3000,3700,3760,3767
1589,X20,Công ty Cổ phần X20,X20 Joint Stock Company,Hàng cá nhân,Personal Goods,Hàng cá nhân & Gia dụng,Personal & Household Goods,Hàng May mặc,Clothing & Accessories,CT,3000,3700,3760,3763

### Danh sách cổ phiếu theo nhóm

In [4]:
# Liệt kê tất cả mã chứng khoán theo nhóm phân loại. Ví dụ HOSE, VN30, VNMidCap, VNSmallCap, VNAllShare, VN100, ETF, HNX, HNX30, HNXCon, HNXFin, HNXLCap, HNXMSCap, HNXMan, UPCOM, FU_INDEX (mã chỉ số hợp đồng tương lai), CW (chứng quyền)
stock.listing.symbols_by_group('VN30')

0     ACB
1     BCM
2     BID
3     BVH
4     CTG
5     FPT
6     GAS
7     GVR
8     HDB
9     HPG
10    MBB
11    MSN
12    MWG
13    PLX
14    POW
15    SAB
16    SHB
17    SSB
18    SSI
19    STB
20    TCB
21    TPB
22    VCB
23    VHM
24    VIB
25    VIC
26    VJC
27    VNM
28    VPB
29    VRE
Name: symbol, dtype: object

### Danh sách mã ngành theo mã icb

In [7]:
stock.listing.industries_icb()

,icb_name,en_icb_name,icb_code,level
0,Sản xuất Dầu khí,Oil & Gas Producers,0530,3
1,"Thiết bị, Dịch vụ và Phân phối Dầu khí","Oil Equipment, Services & Distribution",0570,3
2,Hóa chất,Chemicals,1350,3
3,Lâm nghiệp và Giấy,Forestry & Paper,1730,3
4,Kim loại,Industrial Metals & Mining,1750,3
...,...,...,...,...
151,Viễn thông,Telecommunications,6000,1
152,Tiện ích Cộng đồng,Utilities,7000,1
153,Tài chính,Financials,8000,1
154,Ngân hàng,Banks,8301,1
155,Công nghệ Thông tin,Technology,9000,1

## Quote: Giá chứng khoán

#### Giá lịch sử

In [ ]:
df = stock.quote.history(start='2020-01-01', end='2024-12-31')
df

           time   open   high    low  close    volume
0    2020-01-02   9.38   9.46   9.33   9.46   1163109
1    2020-01-03   9.46   9.54   9.42   9.46   1055528
2    2020-01-06   9.46   9.46   9.25   9.25   1286035
3    2020-01-07   9.25   9.33   9.25   9.25   1050934
4    2020-01-08   9.25   9.25   9.05   9.09   2304937
...         ...    ...    ...    ...    ...       ...
1085 2024-05-20  28.50  28.55  28.20  28.25   9333300
1086 2024-05-21  28.25  28.30  27.85  28.20  10824000
1087 2024-05-22  28.20  28.25  27.90  27.95   9283100
1088 2024-05-23  28.00  28.50  28.00  28.45  10449700
1089 2024-05-24  28.45  30.20  28.25  29.25  33848200

[1090 rows x 6 columns]

In [5]:
# Tất cả dataframe dữ liệu sẽ được gán thuộc tính tên và loại tài sản tương ứng
print(f'Mã chứng khoán: {IDC}')
print(f'Loại tài sản: {df.category}')

NameError: name 'IDC' is not defined

#### Intraday: dữ liệu khớp lệnh

In [6]:
# Dữ liệu khớp lệnh trong ngày giao dịch realtime hoặc ngày gần nhất (ngoài giờ giao dịch)
stock.quote.intraday(symbol='IDC', show_log=False)

                  time    price  volume match_type         id
99 2024-06-14 14:27:26  63200.0     400        Buy  214038073
98 2024-06-14 14:27:27  63300.0    6600        Buy  214038245
97 2024-06-14 14:27:28  63300.0     400        Buy  214038369
96 2024-06-14 14:27:30  63300.0     400        Buy  214039076
95 2024-06-14 14:27:31  63300.0    6600        Buy  214039308
..                 ...      ...     ...        ...        ...
4  2024-06-14 14:48:45  62500.0     100       Sell  214071578
3  2024-06-14 14:52:38  62500.0     200       Sell  214072290
2  2024-06-14 14:54:03  62500.0     100       Sell  214072579
1  2024-06-14 14:55:01  62500.0     200       Sell  214072759
0  2024-06-14 14:57:29  62500.0     200       Sell  214073170

[100 rows x 5 columns]

In [7]:
# Bước giá và khối lượng giao dịch: realtime
stock.quote.price_depth('IDC')

    price acc_volume acc_buy_volume acc_sell_volume acc_undefined_volume
0   64200       2300           2300               0                    0
1   64000       5500           1900            3600                    0
2   63900      12200           7900            4300                    0
3   63800      76900          69700            6200                 1000
4   63700     201100         127000           74100                    0
5   63600     279500         122800          150600                 6100
6   63500     243500          76500          154600                12400
7   63400     139800          56600           82800                  400
8   63300      61800          41000           20800                    0
9   63200      72500          24900           47600                    0
10  63100      12500              0           12500                    0
11  62500     312500              0             900               311600

## Trading: Giao dịch

### Bảng giá

In [11]:
stock.trading.price_board(['VNM'])

  listing                                                                 \
   symbol ceiling  floor ref_price stock_type exchange last_trading_date
0     VNM   71500  62300     66900      STOCK      HSX

                                ...     bid_ask                           \
  listed_share   type       id  ... bid_2_price bid_2_volume bid_3_price
0   2089850445  STOCK  8424928  ...       66000       223100       65900

                                                                              \
  bid_3_volume ask_1_price ask_1_volume ask_2_price ask_2_volume ask_3_price
0        18900       66200        33900       66300          500       66400


  ask_3_volume
0         1500

[1 rows x 37 columns]

In [13]:
stock.trading.price_board(['VCB','ACB','TCB','IDC']) # Bỏ .T để xoay trở lại đúng kiểu hiển thị bảng giá

  listing                                                                 \
   symbol ceiling  floor ref_price stock_type exchange last_trading_date
0     VCB   94500  82300     88400      STOCK      HSX
1     ACB   26500  23100     24800      STOCK      HSX
2     TCB   52800  45950     49400      STOCK      HSX
3     IDC   70100  57500     63800      STOCK      HNX               NaN

                                   ...     bid_ask                           \
   listed_share   type         id  ... ask_6_price ask_6_volume ask_7_price
0  5.589091e+09  STOCK  8424561.0  ...         NaN          NaN         NaN
1  4.466658e+09  STOCK  8424512.0  ...         NaN          NaN         NaN
2  3.522511e+09  STOCK  8424683.0  ...         NaN          NaN         NaN
3           NaN  STOCK        NaN  ...     63100.0        500.0     63200.0

                                                                               \
  ask_7_volume ask_8_price ask_8_volume ask_9_price ask_9_volume ask_10_price
0          NaN         NaN          NaN         NaN          NaN          NaN
1          NaN         NaN          NaN         NaN          NaN          NaN
2          NaN         NaN          NaN         NaN          NaN          NaN
3        700.0     63500.0       1100.0     63600.0       2600.0      63700.0


  ask_10_volume
0           NaN
1           NaN
2           NaN
3       23100.0

[4 rows x 75 columns]

## Company: Thông tin công ty

> Hiện tại chỉ có nguồn dữ liệu `TCBS` được hỗ trợ

In [21]:
from vnstock3 import Vnstock

company = Vnstock().stock(symbol='IDC', source='TCBS').company

### Tổng quan

In [22]:
company.overview()

,exchange,industry,company_type,no_shareholders,foreign_percent,outstanding_share,issue_share,established_year,no_employees,stock_rating,delta_in_week,delta_in_month,delta_in_year,short_name,website,industry_id,industry_id_v2
0,HNX,Bất động sản,CT,12811,0.237,330.0,330.0,2010,1112,3.3,0.019,0.015,0.459,IDICO,http://www.idico.com.vn,336,8633

### Hồ sơ

In [23]:
company.profile()

,company_name,company_profile,history_dev,company_promise,business_risk,key_developments,business_strategies
0,Tổng Công ty IDICO - CTCP,"Tổng Công ty IDICO (IDC), có tiền thân là Tổng...",Ngày 06/12/2000: Tổng Công ty Đầu tư phát tr...,Cuộc chiến tranh thương mại Mỹ-Trung nếu leo...,"Trong quá trình xây dựng công trình, doanh n...","Đầu tư xây dựng, kinh doanh phát triển hạ tầ...",Tăng cường thực hiện vai trò Tổng công ty tr...

### Cổ đông

In [24]:
company.shareholders()

                                    share_holder  share_own_percent
0                   Công ty Cổ phần Tập đoàn SSG             0.2250
1  Công ty TNHH Sản Xuất Và Thương Mại Bách Việt             0.1193
2                                Vũ Thị Thu Hằng             0.0633
3                                 Đặng Việt Dũng             0.0253
4                             Nguyễn Thị Như Mai             0.0019
5                                           Khác             0.0558

### Giao dịch nội bộ

In [25]:
company.insider_deals()

,deal_announce_date,deal_method,deal_action,deal_quantity,deal_price,deal_ratio
0,2023-11-14,None,Mua,4002000.0,None,None
1,2022-12-16,None,Mua,591000.0,None,None
2,2022-11-15,None,Mua,5000000.0,None,None
3,2022-02-18,None,Mua,6200.0,None,None
4,2021-11-18,None,Mua,9776000.0,None,None
5,2021-11-17,None,Mua,5000.0,None,None
6,2021-10-15,None,Mua,11539000.0,None,None
7,2021-10-06,None,Bán,-18000.0,None,None
8,2021-08-05,None,Mua,3668000.0,None,None
9,2021-06-22,None,Bán,-67500000.0,None,None
10,2021-06-11,None,Bán,-85000.0,None,None
11,2021-05-18,None,Mua,940000.0,None,None
12,2021-05-18,None,Bán,-940000.0,None,None
13,2021-05-12,None,Mua,940000.0,None,None
14,2021-05-12,None,Bán,-940000.0,None,None
15,2021-05-06,None,Mua,85000.0,None,None
16,2021-02-09,None,Bán,-22545000.0,None,None
17,2020-12-23,None,Mua,24400002.0,None,None
18,2020-12-22,None,Bán,-108000000.0,None,None
19,2020-09-25,None,Bán,-8100.0,None,None

### Công ty con, liên kết

In [26]:
company.subsidiaries()

                                     sub_company_name  sub_own_percent
0   Công Ty TNHH Một Thành Viên Dịch Vụ Khu Công N...            1.000
1   Công ty TNHH MTV Phát Triển Đô Thị Và Khu Công...            1.000
2                              Công Ty Cổ Phần Idergy            1.000
3                    Công ty Cổ Phần Idico Vinh Quang            1.000
4              Công ty Cp Đầu Tư Xây Dựng Số 10 Idico            0.978
5   Công Ty Cổ Phần Đầu Tư Và Xây Dựng Thái Bình I...            0.952
6   Công ty Cổ phần Đầu tư Xây dựng và Phát triển ...            0.819
7                 Công ty Cổ phần Tư vấn Đầu tư IDICO            0.704
8   Công ty Cổ phần Đầu tư Phát triển Nhà và Đô th...            0.669
9                    Công ty Cổ Phần Idico Tiền Giang            0.650
10    Công ty Cổ phần Đầu tư Phát triển Hạ tầng IDICO            0.597
11  Công ty Cổ Phần Đầu Tư Phát Triển Đô Thị Và Kh...            0.549
12     Công ty Cổ phần Thủy điện Srok Phu Miêng IDICO            0.518
13      Công ty Cổ phần Đầu tư Xây dựng Dầu khí IDICO            0.510
14      Công ty Cổ phần Đầu tư Xây dựng Long An IDICO            0.510
15  Công Ty Cổ Phần Phát Triển Đường Cao Tốc Biên ...            0.490
16            Công ty Cổ Phần Xây Dựng Số 1 Sông Hồng            0.349
17      Công ty Cổ phần Đầu tư Xây dựng Lắp máy IDICO            0.301
18                               Công ty Cổ phần IDTT            0.300
19            Công ty TNHH Kính Nổi Siêu Trắng Phú Mỹ            0.300
20                   Công ty Cổ phần Thủy điện Đak Mi            0.260
21  Công ty Cổ phần Đầu tư Khu Công Nghiệp Dầu khí...            0.085
22           Công ty Cổ phần Tư vấn Xây dựng Tổng hợp            0.050
23                  Công ty Cổ Phần Đầu Tư Đồng Thuận            0.046
24      Công ty Cổ phần Điện lực Dầu khí Nhơn Trạch 2            0.014
25  Công ty Cổ phần Đầu tư Phát triển Cường Thuận ...            0.012

### Ban lãnh đạo

In [27]:
company.officers()

          officer_name              officer_position  officer_own_percent
1      Vũ Thị Thu Hằng                          None               0.0633
0       Đặng Việt Dũng                          None               0.0253
2   Nguyễn Thị Như Mai  Thành viên Hội đồng Quản trị               0.0019
3          Võ Tấn Dũng                          None               0.0001
4    Nguyễn Tuế Loan                          None               0.0001
12       Lê Thị Hương                          None               0.0001
18      Hoàng Văn Hiến          Trưởng Ban kiểm soát               0.0000
5     Đặng Phương Thảo                          None               0.0000
6       Ninh Mạnh Hồng                          None               0.0000
7       Nguyễn Văn Đạt                          None               0.0000
8        Phạm Văn Toán                          None               0.0000
9        Đào Minh Tiến                          None               0.0000
10      Phạm Minh Hiệp                          None               0.0000
11      Phan Văn Chính                          None               0.0000
13      Trịnh Hùng Lâm                          None               0.0000
14    Hoàng Văn Tịnh                          None               0.0000
15       Trần Thị Ngọc                          None               0.0000
16     Nguyễn Văn Minh                          None               0.0000
17      HOÀNG VĂN HIẾN                          None               0.0000
19        Vũ Quang Bảo                          None               0.0000

### Sự kiện

In [28]:
company.events()

,rsi,rs,id,price,price_change,price_change_ratio,price_change_ratio_1m,event_name,event_code,notify_date,exer_date,reg_final_date,exer_right_date,event_desc
0,64.2,81.0,2568408,60626,-385,-0.006,0.069,IDC - Trả cổ tức Đợt 3 năm 2023 bằng tiền 500 ...,DIV,2024-05-27 00:00:00,2024-06-19 00:00:00,2024-06-04 00:00:00,2024-06-03 00:00:00,Tổng Công ty IDICO - CTCP (IDC) trả cổ tức Đợt...
1,64.2,81.0,2568409,60626,-385,-0.006,0.069,IDC - Trả cổ tức Đợt 1 năm 2024 bằng tiền 2000...,DIV,2024-05-27 00:00:00,2024-06-19 00:00:00,2024-06-04 00:00:00,2024-06-03 00:00:00,Tổng Công ty IDICO - CTCP (IDC) trả cổ tức Đợt...
2,64.7,60.0,2565878,55054,-768,-0.014,0.018,IDC - Tổ chức ĐHĐCĐ thường niên 2024,AGME,2024-03-06 00:00:00,2024-04-26 00:00:00,2024-03-25 00:00:00,2024-03-22 00:00:00,Tổng Công ty IDICO - CTCP (IDC) tổ chức ĐHĐCĐ ...
3,64.6,80.0,2565114,49466,-93,-0.002,0.045,IDC - Trả cổ tức Đợt 2 năm 2023 bằng tiền 1500...,DIV,2024-01-10 00:00:00,2024-01-31 00:00:00,2024-01-16 00:00:00,2024-01-15 00:00:00,Tổng Công ty IDICO - CTCP (IDC) trả cổ tức Đợt...
4,60.6,69.0,2564210,45078,805,0.018,0.156,IDC - Trả cổ tức Đợt 1 năm 2023 bằng tiền 2000...,DIV,2023-09-21 00:00:00,2023-10-13 00:00:00,2023-09-29 00:00:00,2023-09-28 00:00:00,Tổng Công ty IDICO - CTCP (IDC) trả cổ tức Đợt...
5,62.4,67.0,2562348,35647,426,0.012,0.086,IDC - Trả cổ tức Đợt 2 năm 2022 bằng tiền 2000...,DIV,2023-04-05 00:00:00,2023-04-27 00:00:00,2023-04-12 00:00:00,2023-04-11 00:00:00,Tổng Công ty IDICO - CTCP (IDC) trả cổ tức Đợt...
6,47.5,49.0,2561494,33860,1191,0.036,0.018,IDC - Tổ chức ĐHĐCĐ thường niên 2023,AGME,2023-03-01 00:00:00,2023-04-21 00:00:00,2023-03-20 00:00:00,2023-03-17 00:00:00,Tổng Công ty IDICO - CTCP (IDC) tổ chức ĐHĐCĐ ...
7,29.4,26.0,2560273,27479,-2978,-0.098,-0.251,IDC - Lấy ý kiến cổ đông bằng văn bản,BALLOT,2022-11-11 00:00:00,1753-01-01 00:00:00,2022-11-18 00:00:00,2022-11-17 00:00:00,Tổng Công ty IDICO - CTCP (IDC) tổ chức lấy ý ...
8,67.0,86.0,2559609,57426,2808,0.051,0.159,"IDC - Niêm yết bổ sung 29,999,929 cổ phiếu",AIS,2022-08-24 00:00:00,2022-08-22 00:00:00,1753-01-01 00:00:00,1753-01-01 00:00:00,Tổng Công ty IDICO - CTCP (IDC) niêm yết bổ su...
9,59.3,84.0,2559491,53585,2308,0.045,0.144,IDC - Trả cổ tức Đợt 1 năm 2022 bằng tiền 2000...,DIV,2022-08-12 00:00:00,2022-09-06 00:00:00,2022-08-22 00:00:00,2022-08-19 00:00:00,Tổng Công ty IDICO - CTCP (IDC) trả cổ tức Đợt...
10,38.8,46.0,2558927,34999,150,0.004,-0.047,IDC - Phát hành cổ phiếu trả cổ tức tỷ lệ 10%,ISS,2022-06-21 00:00:00,2022-06-27 00:00:00,2022-06-28 00:00:00,2022-06-27 00:00:00,Tổng Công ty IDICO - CTCP (IDC) phát hành cổ p...
11,37.7,43.0,2558207,42354,815,0.020,-0.273,IDC - Trả cổ tức Đợt 2 năm 2021 bằng tiền 600 ...,DIV,2022-05-05 00:00:00,2022-06-10 00:00:00,2022-05-16 00:00:00,2022-05-13 00:00:00,Tổng Công ty IDICO - CTCP (IDC) trả cổ tức Đợt...
12,60.1,66.0,2496978,57237,518,0.009,0.235,IDC - Tổ chức ĐHĐCĐ thường niên 2022,AGME,2022-03-07 00:00:00,2022-04-19 00:00:00,2022-03-21 00:00:00,2022-03-18 00:00:00,Tổng Công ty IDICO - CTCP (IDC) tổ chức ĐHĐCĐ ...
13,86.1,90.0,2305450,54242,-293,-0.005,0.425,"IDC - Trả cổ tức Đợt 1, 2021 bằng tiền 2400 VN...",DIV,2021-10-29 09:00:00,2021-11-25 00:00:00,2021-11-10 00:00:00,2021-11-09 00:00:00,Tổng Công ty IDICO - CTCP trả cổ tức Đợt 1 nă...
14,43.6,30.0,1682737,27743,585,0.022,-0.087,IDC - Tổ chức ĐHĐCĐ thường niên 2021,AGME,2021-03-17 00:00:00,2021-04-28 00:00:00,2021-04-01 00:00:00,2021-03-31 00:00:00,Tổng Công ty IDICO - CTCP (IDC) tổ chức ĐHĐCĐ ...

### Tin tức

In [29]:
company.news()

,rsi,rs,price,price_change,price_change_ratio,price_change_ratio_1m,id,title,source,publish_date
0,61.0,55.0,NaN,NaN,NaN,NaN,11210581,IDICO chốt ngày trả cổ tức bằng tiền mặt cho c...,TCBS,2024-06-09 10:12:00
1,62.7,60.0,61700.0,-200.0,-0.003,0.036,11209992,IDC: Thông báo về việc chi trả cổ tức đợt 3 nă...,TCBS,2024-06-07 14:35:00
2,64.2,81.0,60626.0,-385.0,-0.006,0.069,11197329,IDC: Ngày đăng ký cuối cùng trả cổ tức bằng ti...,TCBS,2024-05-27 16:33:00
3,66.3,78.0,61491.0,384.0,0.006,0.210,11194134,IDICO (IDC) chốt danh sách cổ đông chia cổ tức...,TCBS,2024-05-23 15:19:00
4,66.3,78.0,61491.0,384.0,0.006,0.210,11194108,"Cổ phiếu tăng tốc áp sát đỉnh lịch sử, ""ông tr...",TCBS,2024-05-23 14:34:00
5,61.6,64.0,61107.0,1249.0,0.021,0.193,11192961,IDC: Thông báo về ngày đăng ký cuối cùng để th...,TCBS,2024-05-22 17:27:00
6,61.6,64.0,61107.0,1249.0,0.021,0.193,11192774,IDC: Về việc công bố thông tin Nghị Quyết HĐQT...,TCBS,2024-05-22 15:22:00
7,61.6,64.0,61107.0,1249.0,0.021,0.193,11192722,IDC: Về việc công bố thông tin Nghị Quyết HĐQT...,TCBS,2024-05-22 15:18:00
8,67.4,82.0,59089.0,-481.0,-0.008,0.062,11177989,IDC: V/v công bố thông tin các Nghị quyết HĐQT...,TCBS,2024-05-08 16:58:00
9,67.4,82.0,59089.0,-481.0,-0.008,0.062,11178001,IDC: V/v công bố thông tin về việc góp vốn thà...,TCBS,2024-05-08 16:56:00
10,59.6,82.0,56879.0,192.0,0.003,0.010,11172410,IDC: Nghị quyết Đại hội đồng cổ đông thường ni...,TCBS,2024-05-03 16:57:00
11,59.6,82.0,56879.0,192.0,0.003,0.010,11172331,IDC: Báo cáo tài chính quý 1/2024 (công ty mẹ),TCBS,2024-05-03 16:19:00
12,59.6,82.0,56879.0,192.0,0.003,0.010,11172348,IDC: Báo cáo tài chính quý 1/2024,TCBS,2024-05-03 16:02:00
13,34.0,48.0,52268.0,1442.0,0.028,-0.062,11164251,IDC: Báo cáo thường niên 2023,TCBS,2024-04-24 09:36:00
14,46.3,57.0,56111.0,865.0,0.016,-0.007,11151295,IDC: Báo cáo tài chính Năm (Kỳ báo cáo từ 01/0...,TCBS,2024-04-12 10:16:00

### Cổ tức

In [ ]:
company.dividends()

   exercise_date  cash_year  cash_dividend_percentage issue_method
0       25/07/23       2023                     0.181        share
1       22/12/21       2022                     0.276        share
2       22/12/21       2020                     0.120         cash
3       21/12/20       2019                     0.080         cash
4       30/12/19       2018                     0.080         cash
5       05/10/18       2017                     0.080         cash
6       28/09/17       2016                     0.080         cash
7       09/09/16       2015                     0.100         cash
8       26/06/15       2014                     0.100         cash
9       18/06/14       2013                     0.120         cash
10      26/02/13       2012                     0.120         cash
11      24/02/12       2011                     0.120         cash
12      18/07/11       2011                     0.120        share
13      10/03/10       2009                     0.120         cash
14      01/12/08       2008                     0.120         cash

## Finance: Báo cáo tài chính

In [75]:
from vnstock3 import Vnstock
stock = Vnstock().stock(symbol='IDC', source='VCI1')

ValueError: Hiện tại chỉ có nguồn dữ liệu từ VCI, TCBS, MSN được hỗ trợ.

### Bảng cân đối kế toán

In [63]:
stock.finance.balance_sheet(period='year', lang='vi')

,CP,Năm,Hàng tồn kho ròng,Tài sản lưu động khác,Giá trị ròng tài sản đầu tư,Tài sản dài hạn khác,Các quỹ khác,Các quỹ khác,Vốn Ngân sách nhà nước và quỹ khác,Vốn Ngân sách nhà nước và quỹ khác,...,NỢ PHẢI TRẢ (Tỷ đồng),TỔNG CỘNG TÀI SẢN (Tỷ đồng),Lợi thế thương mại (Tỷ đồng),Trả trước dài hạn (Tỷ đồng),Tài sản dài hạn khác (Tỷ đồng),Đầu tư dài hạn (Tỷ đồng),Tài sản cố định (Tỷ đồng),Phải thu dài hạn khác (Tỷ đồng),Phải thu về cho vay dài hạn (Tỷ đồng),Phải thu dài hạn (Tỷ đồng)
0,IDC,2023,1299384858394,74442147579,6151412099364,803484604518,0,79071882784,0,0,...,11515531064178,17720445591660,46173915554,615254957929,119271925084,158258602419,3220848385476,38150700666,0,46021888323
1,IDC,2022,1094750884655,65641284862,107733563135,553094480963,0,36231882784,0,0,...,10885488238527,17013411433665,72926918670,447848716832,119271925084,240341939467,8580949212518,1306991114114,0,1314862301771
2,IDC,2021,549370891448,59172158316,114285104835,656825522139,0,28248519183,0,0,...,11047798602930,16075835137834,4945754476,632062734348,99845659784,278331600412,5820587285413,547979807793,0,563361605698
3,IDC,2020,539760732282,81579996337,120836646535,555140831770,0,18048559983,0,0,...,10233754388016,14622956584501,11128205378,523814965066,148595659784,836518264492,6138796020253,44446912190,0,57601849584
4,IDC,2019,479192575278,37976289044,127388188234,513322861639,0,2748559983,0,0,...,10083019288092,14315622203562,17310656280,475356191743,104142259784,862206296925,6345862259561,31903176546,0,38673018718
5,IDC,2018,386374875733,66984805260,139364297465,494632507414,0,2748559983,0,0,...,9681239462366,13864800202316,21683604793,453993886685,104142259784,891973303561,6398712414509,21730777610,0,12466158587
6,IDC,2017,548053430188,101605259967,146164081268,530290592391,0,1295939231940,0,0,...,10562991983241,14361472903145,34256817936,480132258401,111483547495,915778198774,6203146126860,1875374299,176467557859,183362581989
7,IDC,2016,799267576095,119829847490,69701458579,512139436347,0,1294445288709,0,0,...,9248263259814,12773935834259,46830031081,460500438584,111483547495,557196109538,4107977329165,2013148260,353746616159,362330967411
8,IDC,2015,903380462885,50484937610,34716402699,275062922386,0,1267619692123,0,0,...,10287380385150,13534027006967,46372776049,225856320266,112016091372,622635600639,4033566586701,2207312516,15694235694,25462484030
9,IDC,2014,662033412318,35592640865,2198732404,186512597905,0,1168593396095,0,0,...,10519746330757,13352563369798,57642942376,128869655529,148443923608,680425852095,8587637067364,49676861193,15694235694,73815463964

In [39]:
stock.finance.balance_sheet(period='quarter', lang='en').head()

,ticker,yearReport,lengthReport,Net Inventories,Other current assets,Investment in properties,Other non-current assets,Other Reserves,Other Reserves,Budget sources and other funds,...,LIABILITIES (Bn. VND),TOTAL ASSETS (Bn. VND),Good will (Bn. VND),Long-term prepayments (Bn. VND),Other long-term assets (Bn. VND),Long-term investments (Bn. VND),Fixed assets (Bn. VND),Other long-term receivables (Bn. VND),Long-term loans receivables (Bn. VND),Long-term trade receivables (Bn. VND)
0,IDC,2024,1,1858248737055,47484360733,5978494235794,798089656778,0,79071882784,0,...,10894297173971,17386392291350,42650257554,604014329871,119271925084,138393407939,3155290701843,36984144066,0,44855331723
1,IDC,2023,4,1299384858394,88648584542,6150721467920,801401352508,0,79071882784,0,...,11527672862623,17731904021319,46173915554,613108790032,119271925084,158284478569,3220848385476,38150700666,0,46021888323
2,IDC,2023,3,1107726931864,60973812356,102819906860,522411533637,0,79071882784,0,...,11287372799258,16898217983203,49801801920,438366173541,119271925084,262256864992,7784423342824,699324227314,0,707195414971
3,IDC,2023,2,1092319148702,62536226674,104408676477,526453876785,0,79071882784,0,...,10713846775869,16916639089693,53429688286,439659513643,119271925084,178243364992,8029942895406,696991114114,0,704862301771
4,IDC,2023,1,1111529659560,68408163423,106095677710,536414303486,0,36231882784,0,...,11151142281893,17427813052211,68403529304,435691928721,119271925084,180341939467,8457444353549,1275991114114,0,1283862301771

### Báo cáo lãi lỗ

In [40]:
stock.finance.income_statement(period='year', lang='vi').head()

,CP,Năm,Chứng khoán kinh doanh,Chứng khoán kinh doanh,Chứng khoán kinh doanh,Chứng khoán đầu tư,Chứng khoán đầu tư,Cổ đông thiểu số,Cổ đông thiểu số,Lãi/Lỗ ròng trước thuế,...,Tổng thu nhập hoạt động,LN từ HĐKD trước CF dự phòng,Chi phí dự phòng rủi ro tín dụng,LN trước thuế,Thuế TNDN,Chi phí thuế TNDN hiện hành,Chi phí thuế TNDN hoãn lại,Lợi nhuận thuần,Cổ đông của Công ty mẹ,Lãi cơ bản trên cổ phiếu
0,IDC,2023,0,0,0,0,0,0,262398182292,2056777215053,...,0,0,0,2056777215053,-400731839520,-507679994386,106948154866,1656045375533,1393647193241,4223
1,IDC,2022,0,0,0,0,0,0,287184162360,2617618001880,...,0,0,0,2617618001880,-562926806583,-563832937604,906131021,2054691195297,1767507032937,5605
2,IDC,2021,0,0,0,0,0,0,123719209701,756169174742,...,0,0,0,756169174742,-178141894902,-166809809492,-11332085410,578027279840,454308070139,1514
3,IDC,2020,0,0,0,0,0,0,125227643687,521767062123,...,0,0,0,521767062123,-92113347483,-97330713384,5217365901,429653714640,304426070953,1015
4,IDC,2019,0,0,0,0,0,0,132340992878,574460791938,...,0,0,0,574460791938,-97423150923,-70825889148,-26597261775,477037641015,344696648137,1149

In [ ]:
stock.finance.income_statement(period='quarter', lang='en').head()

  ticker  yearReport  ...  Attributable to parent company  EPS_basis
0    VCI        2024  ...                    197756462393          0
1    VCI        2023  ...                    122950502675          0
2    VCI        2023  ...                    179003174655          0
3    VCI        2023  ...                    116896619351          0
4    VCI        2023  ...                     73054362713          0

[5 rows x 59 columns]

### Báo cáo lưu chuyển tiền tệ

In [ ]:
stock.finance.cash_flow(period='year', lang='vi').head()

    CP  ...  Tiền chi cho vay, mua công cụ nợ của đơn vị khác (Tỷ đồng)
0  VCI  ...                                                  0
1  VCI  ...                                                  0
2  VCI  ...                                                  0
3  VCI  ...                                                  0
4  VCI  ...                                                  0

[5 rows x 44 columns]

In [ ]:
stock.finance.income_statement(period='quarter', lang='en').head()

  ticker  yearReport  ...  Attributable to parent company  EPS_basis
0    VCI        2024  ...                    197756462393          0
1    VCI        2023  ...                    122950502675          0
2    VCI        2023  ...                    179003174655          0
3    VCI        2023  ...                    116896619351          0
4    VCI        2023  ...                     73054362713          0

[5 rows x 59 columns]

### Chỉ số tài chính

In [ ]:
stock.finance.ratio(period='year', lang='vi').head()

  Meta           ... Chỉ tiêu cơ cấu nguồn vốn
    CP   Năm Kỳ  ...                   Nợ/VCSH TSCĐ / Vốn CSH Vốn CSH/Vốn điều lệ
0  VCI  2023  5  ...                  1.340876       0.003178            1.684852
1  VCI  2022  5  ...                  1.192721       0.003617            1.484678
2  VCI  2021  5  ...                  1.543047       0.002011            1.495283
3  VCI  2020  5  ...                  0.853905       0.003181            1.033483
4  VCI  2019  5  ...                  0.787676       0.002445            0.926081

[5 rows x 37 columns]

In [ ]:
stock.finance.ratio(period='quarter', lang='en').head()

    Meta                         Chỉ tiêu định giá                           \
  ticker yearReport lengthReport               P/B Market Capital (Bn. VND)
0    VCB       2024            1          2.931225          508607304842000
1    VCB       2023            4          3.205992          528728033385200
2    VCB       2023            3          3.115219          495752394939400
3    VCB       2023            2          3.164272          480661848532000
4    VCB       2023            1          3.404580          492181723384000

                                                                    \
  Outstanding Share (Mil. Shares)        P/E       P/S P/Cash Flow
0                      5589091262  15.588653  7.649762   -3.384084
1                      5589091262  16.005957  7.807162  -13.718398
2                      5589091262  14.751702  7.039211    6.687242
3                      5589091262  14.834141  6.735315   10.304262
4                      4732516571  15.919692  7.044594    1.981862

                ... Chỉ tiêu hiệu quả hoạt động                         \
     EPS (VND)  ...        Fixed Asset Turnover Days Sales Outstanding
0  1535.132564  ...                         0.0                   None
1  1673.800903  ...                         0.0                   None
2  1300.554716  ...                         0.0                   None
3  1328.091214  ...                         0.0                   None
4  1898.870266  ...                         0.0                   None

                                                                  \
  Days Inventory Outstanding Days Payable Outstanding Cash Cycle
0                        0.0                      0.0       None
1                        0.0                      0.0       None
2                        0.0                      0.0       None
3                        0.0                      0.0       None
4                        0.0                      0.0       None

                     Chỉ tiêu cơ cấu nguồn vốn              \
  Inventory Turnover (ST+LT borrowings)/Equity Debt/Equity
0                0.0                       0.0    9.216413
1                0.0                       0.0   10.148315
2                0.0                       0.0    9.872063
3                0.0                       0.0   10.212240
4                0.0                       0.0   11.764083


  Fixed Asset-To-Equity Owners' Equity/Charter Capital
0              0.043710                       3.106303
1              0.045734                       3.015577
2              0.046732                       2.849184
3              0.049990                       2.719604
4              0.053450                       2.588227

[5 rows x 37 columns]